# Generated by Django 5.2.11 on 2026-03-22 04:05

import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=listings.models.upload_icon_to, validators=[listings.models.validate_image_file])),
                ('stock_quantity', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model_number', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
