# Generated by Django 5.2.11 on 2026-04-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
