# Generated by Django 5.2.11 on 2026-04-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_product_is_rejected_product_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=100),
        ),
    ]
