name: CI

on:
  push:
    branches: ["feature_branch1", "staging", "main"]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: tests.test_settings #instruct the runner to use instead of config.settings
    defaults:
      run:
        working-directory: ./djangoApp #setting the current directory as djangoApp

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install python packages
        run: pip install -r requirements.txt

      - name: execute all the tests
        run: python3 manage.py test --settings=tests.test_settings